name: Build and Release APK

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apks
          path: app/build/outputs/apk/release/*.apk

  release:
    needs: build-release-apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APKs from Staging Area
        uses: actions/download-artifact@v2
        with:
          name: release-apks
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: Description of the release
          draft: false
          prerelease: false

      - name: Find and Upload APKs
        run: |
          APK_FILES=$(ls ./app/build/outputs/apk/release/*.apk)
          for APK_FILE in $APK_FILES; do
            FILE_NAME=$(basename $APK_FILE)
            echo "Uploading $FILE_NAME"
            gh release upload ${{ github.run_number }} $APK_FILE --repo ${{ github.repository }}
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
